---
- name: create k8s cluster  
  gcp_container_cluster:    
    name: "{{ cluster_name }}"    
    initial_node_count: "{{ initial_node_count }}"    
    location: "{{ zone }}"    
    network: "{{ network.name }}"
    project: "{{ project_id }}"
    default_max_pods_constraint:
      max_pods_per_node: "110"
    addons_config:
      horizontal_pod_autoscaling:
        disabled: "no"
      http_load_balancing:
        disabled: "no"  
    auth_kind: serviceaccount    
    service_account_file: "{{ credentials_file }}"    
    state: present  
  register: cluster

- name: create k8s node pool  
  gcp_container_node_pool:    
    name: "node-pool-{{ cluster_name }}"    
    initial_node_count: "{{ initial_node_count }}"    
    cluster: "{{ cluster }}"    
    config:      
      disk_size_gb: "{{ disk_size_gb }}"      
      disk_type: "{{ disk_type }}"      
      machine_type: "{{ machine_type }}" 
    autoscaling:
      enabled: "yes"
      min_node_count: "1"
      max_node_count: "10"
    management:
      auto_repair: "yes"
      auto_upgrade: "yes"   
    location: "{{ zone }}"    
    project: "{{ project_id }}"    
    auth_kind: serviceaccount    
    service_account_file: "{{ credentials_file }}"
    state: present
    
- name: "Connect to cluster (update kubeconfig)"
  shell: "gcloud container clusters get-credentials {{ cluster.name }} --zone {{ zone }} --project {{ project_id }}"
