---
- name: create GCP network  
  gcp_compute_network:    
    name: network-{{ cluster_name }}    
    auto_create_subnetworks: 'true'    
    project: "{{ project_id }}"    
    auth_kind: serviceaccount    
    service_account_file: "{{ credentials_file }}"    
    state: present  
  register: network